apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep-{{ .Values.nameSuffix }}-1
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncwave }}1"
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: sleep
        image: busybox:1.28
        command: ['sh', '-c', 'echo Sleeping && sleep 30']
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep-{{ .Values.nameSuffix }}-2
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncwave }}2"
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: sleep
        image: busybox:1.28
        command: ['sh', '-c', 'echo Sleeping && sleep 30']
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep-{{ .Values.nameSuffix }}-3
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncwave }}3"
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: sleep
        image: busybox:1.28
        command: ['sh', '-c', 'echo Sleeping && sleep 30']
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
