apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: test
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/keenbytes/test-repo.git
    path: charts/nginx
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
