apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-app
  labels:
    app: test-nginx
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

