apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-in-app-level-2
  namespace: argocd
spec:
  destination:
    namespace: default
    server: in-cluster 
  project: default
  source:
    repoURL: https://github.com/keenbytes/test-repo.git
    path: charts/nginx
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true

